server:
  port: 8083

spring:
  application:
    name: transaction-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: ${DB_TRANSACTION_URL:jdbc:postgresql://localhost:5432/fintech_transactions}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    vault:
      uri: ${VAULT_URI:http://vault.vault.svc.cluster.local:8200}
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
        app-auth-path: approle
      kv:
        enabled: true
        backend: secret
        default-context: fintech/jwt
      fail-fast: true
      config:
        lifecycle:
          enabled: true
  config:
    import: "vault://secret/fintech/jwt"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true

jwt:
  public-key: ${public_key}
  kid: ${kid}
  expiration: ${JWT_EXPIRATION:3600000}
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: transaction-service
    version: 0.0.1-SNAPSHOT
    description: FinTech Transaction Service
