apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.21.4
        args: ["server", "-dev", "-dev-listen-address=0.0.0.0:8200"]
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "root-token-dev-fintech-2026"
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        ports:
        - containerPort: 8200
          name: http
        securityContext:
          capabilities:
            add:
            - IPC_LOCK   # Vault wants this to prevent memory from being swapped
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    nodePort: 30200
